alias xclip='xclip -sel clipboard'
alias gitshort='curl -i http://git.io'
alias v='vim'
alias ve='pyenv activate `basename $(pwd)`'
alias mk='pyenv virtualenv'
alias mkhere='pyenv virtualenv `basename $(pwd)`'
